### ISSUE TITLE
Can't download pretrained model.

### ISSUE THREAD

**Issue by zoharli** [yyuanad/Pytorch_C3D_Feature_Extractor#1]
I tried many ways including proxys, but still can't download the file.
Could you please upload the model file to some place like Dropbox or  google drive ?

**Comment by yyuanad** [comment]
Hi, I just upload it to Dropbox. Here is the [link](https://www.dropbox.com/s/mtvzj6qujynfz1q/c3d.pickle?dl=0).

**Comment by zoharli** [comment]
Many thanks for quick reply.
